apiVersion: v1
kind: ConfigMap
metadata: {{ include "metadata.labels" . | nindent 2 }}
data:
  'nginx.conf': |
    worker_processes 1;
    events{
        worker_connections 1024;
    }
    http {
     include       mime.types;
     default_type  application/octet-stream;
    sendfile        on;
    tcp_nopush     on;
    keepalive_timeout  65;
    gzip  on;
    server {
        listen 80;
        location / {
            root /var/www/vsftpd;
            autoindex on;
            auth_basic “Restricted Area;
            auth_basic_user_file /etc/vsftpd/.htpasswd; 
        }
    }
    }
