apiVersion: v1
kind: Secret
metadata: {{ include "metadata.common" . | nindent 2 }}
data:
  FTP_USER: {{ include "ftp.credentials.username" . | b64enc }}
  FTP_PASS: {{ include "ftp.credentials.password" . | b64enc }}