apiVersion: v1
kind: Secret
metadata: {{ include "metadata.common" . | nindent 2 }}
data:
  FTP_USER: {{ .Values.vsftpd.user.name | default "admin" | b64enc }}
  FTP_PASS: {{ .Values.vsftpd.user.password | default (randAlphaNum 12) | b64enc }}