apiVersion: v1
kind: Service
metadata: {{ include "service.ftp.metadata" . | nindent 2 }}
spec:
  selector: {{ include "metadata.labels.name" . | nindent 4 }}
  ports: {{ include "service.pasvports" . | indent 2 }}
  type: NodePort