apiVersion: v1
kind: Service
metadata: {{ include "service.http.metadata" . | nindent 2 }}
spec:
  selector: {{ include "metadata.labels.name" . | nindent 4 }}
  ports: {{ include "service.httpports" . | nindent 2 }}
  type: NodePort