apiVersion: v1
kind: Service
metadata: {{ include "metadata.common" . | nindent 2 }}
spec:
  selector: {{ include "metadata.labels.name" . | nindent 4 }}
  ports: {{ include "httpports" | indent 4 }}
  type: ClusterIP